### ISSUE TITLE
New Version out (Dec 2019)

### ISSUE THREAD

**Issue by lemonzest79** [ganto/copr-umoci#2]
Hiya

Dunno how important this is, but a new version was released in Dec 2019

https://github.com/openSUSE/umoci/releases/tag/v0.4.5

**Comment by ganto** [comment]
Sorry for the delay. umoci-0.4.5 packages are available now.

I was hoping, that `go-md2man` which is a build dependency would still be added to EPEL 8, so that I can also build it for EPEL 8. This didn't happen, so I'm using the [cyberpear/godeps](https://copr.fedorainfracloud.org/coprs/cyberpear/godeps) COPR for building EPEL 8 packages for now.
